32 validate 143
data-to-insight/csc-validator-be-903 pull request #281
Opened 2021-08-16 09:38 UTC by jfan2006

Added the reason for new episode code checking for 143 validation rule. 

Closes #32

2021-08-16 13:08 UTC, mwaddoups requested changes

2021-08-16 13:08 UTC, mwaddoups commented on tests/test_validators.py
> +    assert result == {'Episodes': [1, 2, 3, 4, 5]}
There's actually a subtlety to this rule that needs to be covered in the test and code (according to DfE). 

The description specifies "If provided <RNE> must be a valid value.".  Note the "if provided" - this means, that if it's not provided (i.e. it's pd.NA) , it shouldn't be a validation error. 

As such, I think this test case should just return `[1, 2, 3, 4]` as index 5 is valid.

2021-08-16 13:08 UTC, mwaddoups commented on validator903/validators.py
> +        mask = episodes['RNE'].isin(code_list)
Similarly to my comment on the test, we need to also allow for cases where it is not provided. In this case you will want to combine this mask with another mask using the OR (`|`) operator. The relevant functions in pandas you'll need to check to see if it is missing are `.notna()` and `.isna()`.

See if you can get the test to pass by changing this.

2021-08-16 17:15 UTC, jfan2006 commented on tests/test_validators.py
> +    assert result == {'Episodes': [1, 2, 3, 4, 5]}
This is interesting! Totally understood your explanation about the DfE spec but I'm thinking in reality there shouldn't and won't any episode that doesn't have this reason code. (If it's before the end of June I'd try this on the DfE's SSDA903 system) 

I wondered I should contact DfE to double check/ clarify this validation rule... but for this project I'll make the change.

2021-08-19 06:41 UTC, mwaddoups commented on tests/test_validators.py
> +    assert result == {'Episodes': [1, 2, 3, 4, 5]}
Interesting - my thought is that you might see it missing for unclosed episodes at the end of the year? But that's off the top of my head, I can't remember for sure.

2021-08-19 08:30 UTC, jfan2006 commented on tests/test_validators.py
> +    assert result == {'Episodes': [1, 2, 3, 4, 5]}
I think you were thinking about rule 148 - that's the reason episode ceased - the reason episode ceased could be blank (together with date episode ceased) if they were open/ unclosed episodes at the year end.

> Interesting - my thought is that you might see it missing for unclosed episodes at the end of the year? But that's off the top of my head, I can't remember for sure.

2021-08-19 08:40 UTC, mwaddoups commented on tests/test_validators.py
> +    assert result == {'Episodes': [1, 2, 3, 4, 5]}
Yep - you're right!

2021-08-19 08:47 UTC, mwaddoups approved these changes
All looks good now - nice work! Approving.

2021-08-19 08:47 UTC, merged