Added some rules related to if completed must be from a list - 114, 1…
data-to-insight/csc-validator-be-903 pull request #295
Opened 2021-08-21 14:02 UTC by jfan2006

Added some validation rules related to 'if completed must be from a list' - 114, 120, 131, 132, 175, 176, 177, 196, 631, 633, 1006, and 1009.

Closes #19 , #25 , #26 , #27 , #52 , #53 , #54 , #83 , #273 , #275 , #92 , and #95 .

2021-08-23 08:33 UTC, mwaddoups requested changes
Wow - lot's of new stuff here and a big leap forward!

One minor issue around comparing strings/numbers comes up in a few of these rules that needs minor changes.

And one of the rules should be removed from this PR as it actually has a much more difficult solution.

Nice work so far!

2021-08-23 08:33 UTC, mwaddoups commented on validator903/validators.py
> +    )
I would omit this error for now.

If you read the description carefully, what it says is that the LA code *must be a valid code or* one of the following codes.

What the rule actually wants is for the value to be checked against a list of local authority codes in England and Wales. Having looked at previous permanence files before, LA_PERM is often left blank - so not 100% sure how to deal with this one.

Would be good to get insight from yourself/other analysts on what your previous permanance files look like and if the value is filled in.

For now, I would just remove this rule from this PR - I've removed the tag 'simple rule'.

2021-08-23 08:33 UTC, mwaddoups commented on validator903/validators.py
> +        affected_fields=['SDQ_REASON'],
This isn't a change - more just a note on this one.

The full text specifies to only check this if a child has been looked after continuously for 12 months or more. However, my understanding is that will be true for all children who have OC2 data - so I think I agree we don't need to check that. Does that match your understanding as well?

2021-08-23 08:33 UTC, mwaddoups commented on validator903/validators.py
> +        mask = adoptions['NB_ADOPTR'].isin(code_list) | adoptions['NB_ADOPTR'].isna()
For this one, it's not clear that NB_ADOPTR will always come in as an integer column rather than a string column. If it's a string, it may create a weird bug where for example the string `'1'` is not in the list `[1, 2]`.

To be on the safe side here, it would be worth
- Adding a test to make sure it validates correctly for all of `[1, 2, '1', '2']`.
- Altering the code - I would suggest doing something like `adoptions['NB_ADOPTR'].astype(str).isin(['1', '2'])`, but there are other ways to solve it too.

2021-08-23 08:33 UTC, mwaddoups commented on validator903/validators.py
> +        mask = care_leavers['ACTIV'].isin(code_list) | care_leavers['ACTIV'].isna()
Again, for this one I would use the string `'0'` rather than the number `0`, and make sure you convert the type of ACTIV correctly.

I would also add a special test case for the `'0'`  value.

2021-08-23 08:33 UTC, mwaddoups commented on validator903/validators.py
> +        mask = adoptions['FOSTER_CARE'].isin(code_list) | adoptions['FOSTER_CARE'].isna()
And again, the same comment on this one as with 175
- Make sure you handle strings / integers
- Add test cases for both as well.

2021-08-23 08:33 UTC, mwaddoups commented on tests/test_validators.py
> +    assert result == {'AD1': [2, 3, 4, 5, 6]}
2 and 3 should pass here (as mentioned in my comment on the main function). Since all this data is CSV we can't distinguish between strings and numbers.

2021-08-23 08:33 UTC, mwaddoups commented on tests/test_validators.py
> +    assert result == {'AD1': [0, 3, 4]}
3 should pass here (as mentioned in other comments)

2021-08-26 10:46 UTC, jfan2006 commented on validator903/validators.py
> +    )
You're right - I have just gone back a few years and see all the files they are all indeed blank.

2021-08-26 10:52 UTC, jfan2006 commented on validator903/validators.py
> +        affected_fields=['SDQ_REASON'],
@mwaddoups that's right - OC2 only contains those continuously in care for 12 months. 
Refer to the page 96 '2.9.2 Children covered by this return' of [the DfE guide](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974676/Children_looked-after_by_local_authorities_in_England_2020_to_2021.pdf).

2021-08-26 11:16 UTC, jfan2006 commented
Have made changes for all requested. 

Removed rule 633; 
amended validator for rules 175, 132, 114 and their tests to make sure both string and integer work for allowed value.

2021-08-26 11:20 UTC, jfan2006 commented on validator903/validators.py
> +    )
@PhilDeakin Phil, what's your understanding around this? As we only use CSV files, I wondered LA_PERM are all blank in XML  files too?

2021-08-26 12:02 UTC, mwaddoups approved these changes
Nice one Fan - great to see this many rules coming in! Thanks for making the minor changes.

2021-08-26 12:03 UTC, merged

2021-08-26 12:05 UTC, PhilDeakin commented on validator903/validators.py
> +    )
@jfan2006 The vast majority are null in our CSVs, but there are some that have Manchester's LA code 352.