Added validation rule 178.
data-to-insight/csc-validator-be-903 pull request #296
Opened 2021-08-21 14:51 UTC by jfan2006

Added validation rule 178.

Closes #55

2021-08-23 07:04 UTC, mwaddoups commented on validator903/validators.py
> +        mask = episodes['PLACE_PROVIDER'].isin(code_list_1) & ~episodes['PLACE'].isin(code_list_2) | episodes['PLACE_PROVIDER'].isna() | episodes['PLACE_PROVIDER'].isna() & episodes['PLACE'].isin(cod
So this code works 👍 but I'd suggest breaking this into a few more lines to make the code a bit more readable and maybe changing some variable names to help that too - just to make it easy for anyone who has to glance at or tweak this in the future.
- `code_list_1` -> something like `place_provider_codes`
- `code_list_2` -> something like `place_codes_with_no_provider`

Then for the mask, maybe break into a line for each case, e.g. `place_provider_needed_and_correct`, `place_provider_not_provided`, `place_provider_not_needed` and combine it all together with ORs at the end.

2021-08-23 07:05 UTC, mwaddoups requested changes
Code all works well - but I just had some suggested minor changes around readability.

2021-08-26 10:40 UTC, jfan2006 commented
@mwaddoups I have made the changes as requested.

2021-08-26 10:47 UTC, mwaddoups approved these changes
This all looks good now Fan - nice work!

2021-08-26 10:47 UTC, merged