Adding errors 142 and 148
data-to-insight/csc-validator-be-903 pull request #312
Opened 2021-08-26 15:14 UTC by PhilDeakin

Closes #31
Closes #37

2021-08-26 15:35 UTC, PhilDeakin commented
These two are very similar to the 388 error but a bit simpler.

2021-08-27 06:35 UTC, mwaddoups requested changes
Thanks for putting these in Phil!

142 looks good - I've made some more minor comments as little things to look for, but overall that all looks good.

However I think 148 just needs a simpler approach? I may be missing something here but that looks to me like a simple rule. Keen to hear your thoughts!

2021-08-27 06:35 UTC, mwaddoups commented on validator903/validators.py
> +    def _validate(dfs):
I think this approach is overcomplex for this rule (but may be missing something) -  to me this looks like a simple rule that we can just do without grouping?

2021-08-27 06:35 UTC, mwaddoups commented on validator903/validators.py
> +            df = df.sort_values(['CHILD','DECOM'])
I think you can skip the sort here, since `idxmax` will find the maximum DECOM anyway

2021-08-27 06:35 UTC, mwaddoups commented on validator903/validators.py
> +            df = df.loc[~df.index.isin(grouped_decom_by_child),:]
I would try to avoid this pattern of re-using the same variable name to refer to a different thing as it's easy to introduce bugs. Maybe just call this `ended_episodes_df`.

I think if you also rename `grouped_decom_by_child` to `index_of_last_episodes`, you probably don't need the comment as the code itself should be readable.

2021-08-27 06:35 UTC, mwaddoups commented on tests/test_validators.py
> +    { 'CHILD' : '111', 'DECOM' : '08/06/2020', 'DEC' : '05/06/2020', 'REC': 'X1' },  #3   Fails
I don't think this test case should fail for 148 as both DEC and REC are filled?

2021-08-27 09:34 UTC, PhilDeakin commented on validator903/validators.py
> +    def _validate(dfs):
You're right, I was over/under thinking this. I think I was trying to stop errors 142 & 148 being thrown on the same line, but it doesn't matter.

2021-08-27 09:34 UTC, PhilDeakin commented on validator903/validators.py
> +            df = df.sort_values(['CHILD','DECOM'])
Removed

2021-08-27 09:38 UTC, PhilDeakin commented on tests/test_validators.py
> +    { 'CHILD' : '111', 'DECOM' : '08/06/2020', 'DEC' : '05/06/2020', 'REC': 'X1' },  #3   Fails
Corrected

2021-08-27 10:33 UTC, mwaddoups requested changes
Thanks for getting back on this so quick! Looking better now - have just noted a few minor ways to make the 148 implementation even simpler.

2021-08-27 10:33 UTC, mwaddoups commented on validator903/validators.py
> +            mask = (df['CHILD'].notna()) & (df['DECOM'].notna()) & (((df['DEC'].isna()) & (df['REC'].notna())) | ((df['DEC'].notna()) & (df['REC'].isna())))
I'm not sure you need DECOM here at all actually to cover this rule - I think you can just check DEC and REC (and remove line 1002 as well)

2021-08-27 10:33 UTC, mwaddoups commented on tests/test_validators.py
> +    { 'CHILD' : pd.NA, 'DECOM' : pd.NA, 'DEC' : pd.NA, 'REC': pd.NA },  #20   Nonsense, but should pass
This feels like quite a large set of test cases for the rule now given it's quite simple (there's only 4 cases really I think, DEC/REC present or not present). Might be worth using a simpler set of data for that?

However, in general I don't mind having some redundancy in tests - so I'll leave shortening this up to you.

2021-08-27 11:02 UTC, PhilDeakin commented on validator903/validators.py
> +            mask = (df['CHILD'].notna()) & (df['DECOM'].notna()) & (((df['DEC'].isna()) & (df['REC'].notna())) | ((df['DEC'].notna()) & (df['REC'].isna())))
Done

2021-08-27 11:02 UTC, PhilDeakin commented on tests/test_validators.py
> +    { 'CHILD' : pd.NA, 'DECOM' : pd.NA, 'DEC' : pd.NA, 'REC': pd.NA },  #20   Nonsense, but should pass
I've shorten the amount of test rows.

2021-08-27 13:13 UTC, mwaddoups approved these changes
Looks good now - thanks Phil!

2021-08-27 13:13 UTC, merged