(with error to look into further) validation rule 184
data-to-insight/csc-validator-be-903 pull request #314
Opened 2021-08-27 11:26 UTC by jfan2006

Trying to do the rule 184 #105 but still can't figure out how to do it... 
(saying error in line 24 of validators.py)
Could you help me a bit more on this please? Thanks

2021-08-31 12:24 UTC, mwaddoups commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
I think you just don't need the `ad1.index` part - the `'index'` column is just a regular old column, so 

```
ad1[validation_error]['index'].unique()
```

should do the trick!

2021-08-31 12:24 UTC, mwaddoups commented
I added a comment on line 24 - take a look and see if that helps.

2021-08-31 14:15 UTC, jfan2006 commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
I have just tried as you suggested but it still has errors.

2021-09-01 07:21 UTC, mwaddoups commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
Are you able to provide some more details - like screenshots of the error or something? That might be helpful in diagnosing.

2021-09-01 11:52 UTC, dezog commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
Hi Fan, are you sure the DataFrame has a column called `'index'`? 
Maybe try keeping the `.index` and dropping the `['index']`:
```
ad1.index[validation_error].unique()
```

2021-09-01 12:01 UTC, dezog commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
Looks like `all_data` will have a column called `'index'` due to  the `reset_index()` in line 18, but `ad1` won't have had its index reset. So maybe instead try:
```
ad1.index[validation_error].unique()
```
That make sense, @mwaddoups?

2021-09-01 13:07 UTC, mwaddoups commented on validator903/validators.py
> +            validation_error_locations = ad1.index[validation_error]['index'].unique()
Now I'm confused! I think it needs to be `all_data` to read the appropriate index values off.

```
all_data[validation_error]['index'].unique()
```

2021-09-03 15:13 UTC, dezog requested changes
Just setting this to show 'changes requested'. 

Let me know if the edit Mark suggested in https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/314#discussion_r700194448 doesn't do the trick, but it looks like it should do. 🤞

2021-09-20 09:35 UTC, jfan2006 commented
Tried and made changes based on Mark's suggestion above, and also dates comparison. 
But this still has errors....

2021-09-21 13:50 UTC, dezog requested changes
Hey Fan, think I've figured this one out - it's looking for DATE_PLACED in the AD1 table, but that's actually a field of the PlacedAdoption table. 

That's also causing an error in one of the integration tests where merging AD1 & Header leads to 'DOB_x' & 'DOB_y' columns since they both have that field, so accessing DOB raises a KeyError - but switching to PlacedAdoption should fix this.

I've tried to indicate all the relevant lines to change in the code, hopefully that does it!

2021-09-21 13:50 UTC, dezog commented on tests/test_validators.py
> +    fake_dfs = {'Header': fake_data_header, 'AD1': fake_data_ad1}
AD1 > PlacedAdoption

2021-09-21 13:50 UTC, dezog commented on tests/test_validators.py
> +    assert result == {'AD1': [2]}
AD1 > PlacedAdoption

2021-09-21 13:50 UTC, dezog commented on validator903/validators.py
> +        if 'Header' not in dfs or 'AD1' not in dfs:
AD1 > PlacedAdoption

2021-09-21 13:50 UTC, dezog commented on validator903/validators.py
> +            return {'AD1': validation_error_locations.tolist()}
AD1 > PlacedAdoption

2021-09-21 13:50 UTC, dezog commented on validator903/validators.py
> +            ad1 = dfs['AD1']
AD1 > PlacedAdoption

2021-11-13 14:12 UTC, dezog approved these changes

2021-11-13 14:13 UTC, merged