Added validation for error code 159
data-to-insight/csc-validator-be-903 pull request #315
Opened 2021-08-27 11:51 UTC by WMossDCC

added validation to resolve if a child has been recorded as not receiving an intervention for their substance misuse problem, then the additional item on whether an intervention was offered should be completed as well.

Closes #43

2021-08-31 12:26 UTC, mwaddoups requested changes
Looks good again Wes - just a minor comment on handling an edge case to bear in mind.

2021-08-31 12:26 UTC, mwaddoups commented on tests/test_validators.py
> +        'INTERVENTION_OFFERED': [pd.NA, '0', pd.NA, pd.NA, '1', pd.NA, pd.NA],
For fields which can come in as '1' or '0', I've been suggesting we add test cases for the integers as well as the strings (as pandas can be a bit unpredictable about how/when it converts strings.

As such, let's include [0, 1, '0', '1'] as all values that should pass and be OK.

2021-08-31 12:26 UTC, mwaddoups commented on validator903/validators.py
> +            mask2 = oc2['INTERVENTION_RECEIVED'] == '0'
As mentioned in my comment on the tests, we should handle the case where `oc2['SUBSTANCE_MISUSE']` is an integer rather than string column.

The simplest way is to cast it to string first, e.g.

```
mask1 = oc2['SUBSTANCE_MISUSE'].astype(str) == '1'
```

2021-11-13 14:14 UTC, dezog approved these changes

2021-11-13 14:15 UTC, merged