225 validate 530
data-to-insight/csc-validator-be-903 pull request #316
Opened 2021-08-27 13:27 UTC by JRycr

Added the 530 validation rule
Closes #225

2021-08-31 12:35 UTC, mwaddoups requested changes, later dismissed
Nice to see this coming in Jeanette! 

A couple minor changes suggested here but I think all your code works - just highlighting some easier ways to do things and a couple style changes.

2021-08-31 12:35 UTC, mwaddoups commented on validator903/validators.py
> +      mask = episodes['PLACE'].isin(code_list_place) & episodes['PLACE_PROVIDER'].isin(code_list_place_provider)
You can actually simplify this slightly if you are only checking a single value - you don't need to use use `isin`. You can instead write either

```
mask = episodes['PLACE'].eq('P1') & episodes['PLACE_PROVIDER'].eq('PR4')
```

or

```
mask = (episodes['PLACE'] == 'P1') & (episodes['PLACE_PROVIDER'] == 'PR4')
```

and remove lines 14 and 15. I prefer the first approach as it has less brackets.

2021-08-31 12:35 UTC, mwaddoups commented on validator903/validators.py
> +  return error, _validate
A small style comment that doesn't matter for the code functionality, but is helpful for readability and consistency with the rest of the codebase:

The indentation you've used is a bit inconsistent with the rest of the code - in general we are using 4 spaces between each code block, but I think you've been using 2 spaces. Repl.it unfortunately defaults to 2 spaces so you have to remember to manually set it to 4. You can correct this for multiple lines by selecting multiple lines at once and using Tab  (or Shift+Tab to go back).

2021-09-01 11:12 UTC, JRycr commented
Hi Mark
I have made the changes – thanks the “EQ” was what I wanted to do.

Not sure what happens when you made an amendment as have pushed and committed but then in GitHub can’t find a nice easy button saying pulling request – was easy last time. What do you do when you make an amendment?

Thanks
JEanette


Jeanette Rycroft
Senior Analyst, Joint Intelligence Unit
Customer Transformation
Wigan Council
Wigan Town Hall, Library Street, Wigan WN1 1YN

07766234730
Please note we are currently prioritising COVID 19 activity
Upcoming Leave:
2nd & 3rd September
29th September – 13th October

www.wigan.gov.uk
www.twitter.com/wigancouncil
www.facebook.com/WiganCouncilOnline
[http://www.wigan.gov.uk/pub/images/Deal2030.jpg]

From: Mark Waddoups ***@***.***>
Sent: 31 August 2021 13:36
To: SocialFinanceDigitalLabs/quality-lac-data-beta-validator ***@***.***>
Cc: Rycroft, Jeanette ***@***.***>; Author ***@***.***>
Subject: Re: [SocialFinanceDigitalLabs/quality-lac-data-beta-validator] 225 validate 530 (#316)

CAUTION External E-Mail: Take extra care before clicking links, attachments and actioning requests. Think Before you Click



@mwaddoups requested changes on this pull request.

Nice to see this coming in Jeanette!

A couple minor changes suggested here but I think all your code works - just highlighting some easier ways to do things and a couple style changes.

________________________________

In validator903/validators.py<https://clicktime.symantec.com/3YHbjhVbvnAESCBwwVizCCt6H2?u=https%3A%2F%2Fgithub.com%2FSocialFinanceDigitalLabs%2Fquality-lac-data-beta-validator%2Fpull%2F316%23discussion_r699275340>:

> +def validate_530():

+  error = ErrorDefinition(

+        code = '530',

+        description = "A placement provider code of PR4 cannot be associated with placement P1.",

+        affected_fields=['PLACE', 'PLACE_PROVIDER'],

+    )

+  def _validate(dfs):

+    if 'Episodes' not in dfs:

+      return {}

+    else:

+      code_list_place =['P1']

+      code_list_place_provider=['PR4']

+

+      episodes = dfs['Episodes']

+

+      mask = episodes['PLACE'].isin(code_list_place) & episodes['PLACE_PROVIDER'].isin(code_list_place_provider)

You can actually simplify this slightly if you are only checking a single value - you don't need to use use isin. You can instead write either

mask = episodes['PLACE'].eq('P1') & episodes['PLACE_PROVIDER'].eq('PR4')

or

mask = (episodes['PLACE'] == 'P1') & (episodes['PLACE_PROVIDER'] == 'PR4')

and remove lines 14 and 15. I prefer the first approach as it has less brackets.

________________________________

In validator903/validators.py<https://clicktime.symantec.com/3X5LAsEeMLhScv34YvMrHdd6H2?u=https%3A%2F%2Fgithub.com%2FSocialFinanceDigitalLabs%2Fquality-lac-data-beta-validator%2Fpull%2F316%23discussion_r699278092>:

> +    if 'Episodes' not in dfs:

+      return {}

+    else:

+      code_list_place =['P1']

+      code_list_place_provider=['PR4']

+

+      episodes = dfs['Episodes']

+

+      mask = episodes['PLACE'].isin(code_list_place) & episodes['PLACE_PROVIDER'].isin(code_list_place_provider)

+

+      validation_error_mask = mask

+      validation_error_locations = episodes.index[validation_error_mask]

+

+      return {'Episodes': validation_error_locations.tolist()}

+

+  return error, _validate

A small style comment that doesn't matter for the code functionality, but is helpful for readability and consistency with the rest of the codebase:

The indentation you've used is a bit inconsistent with the rest of the code - in general we are using 4 spaces between each code block, but I think you've been using 2 spaces. Repl.it unfortunately defaults to 2 spaces so you have to remember to manually set it to 4. You can correct this for multiple lines by selecting multiple lines at once and using Tab (or Shift+Tab to go back).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3NzQdkoTxYcr6W4fnBunTQZ6H2?u=https%3A%2F%2Fgithub.com%2FSocialFinanceDigitalLabs%2Fquality-lac-data-beta-validator%2Fpull%2F316%23pullrequestreview-742662595>, or unsubscribe<https://clicktime.symantec.com/3JgfXXSfsPuxDNNGZ39kNdD6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVDRIRJEWN7RBANQXCDSFTTT7TEDJANCNFSM5C5RVGFQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/313b9NBV2PVQPoFpXL4o5bH6H2?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/3KjWv9cW8ZjnT14SBCoYGrU6H2?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________
>>Corporate Logo<<
[https://www.wigan.gov.uk/pub/emailsignature/footer.png]

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

2021-10-04 16:57 UTC, dezog approved these changes
This is looking great, sorry for the delay!

2021-10-04 17:01 UTC, merged