Error 151 - if any adoption data is provided all must be provided
data-to-insight/csc-validator-be-903 pull request #319
Opened 2021-08-27 16:50 UTC by crossls

…CARE>; <NB_ADOPTR>; <SEX_ADOPTR> or <LS_ADOPTR> are provided, then all must be provided

Closes #39

2021-08-27 16:51 UTC, crossls commented
closes #39

2021-08-31 13:08 UTC, mwaddoups requested changes, later dismissed
Really good work on this and the implementation looks good.

I've requested an optional change for readability - but if it doesnt make much sense, no worries and can stick with this approach.

Also - if you continue working on this branch in Repl.it, you may need to Pull changes on your branch before you can continue work, as I merged your branch with the current main branch. You can do that by clicking the Pull button next to the select branch dialog.

2021-08-31 13:08 UTC, mwaddoups commented on validator903/validators.py
> +           validation_error = (~na_date_int | ~na_date_match | ~na_foster_care | ~na_nb_adoptr | ~na_sex_adoptr |~na_lsadoptr) & ~ad1_not_null
This code works and I'm happy to approve it for this purpose! However, there's an optional change to request:

There is some bit more complicated pandas shorthand you could use that would condense all of this to a couple lines:

```
ad1_na = df[['DATE_INT', 'DATE_MATCH', 'FOSTER_CARE', 'NB_ADOPTR', 'SEX_ADOPTR', 'LS_ADOPTR']].notna()
validation_error = ad1_na.any(axis=1) & ~ad1_na.all(axis=1)
```

This is a bit harder to wrap your head around. Some stuff to help
- ad1_na ends up being a dataframe with columns that are all True/False values for each of those columns.
- the `any` and `all` functions return True if any/all of the values on that axis are true. 
- the `axis=1` part says to look across rows, rather than down the columns. 

I'll leave up to you whether you want to put in the change or leave it as it is here - this is a bit more of a complex way to do it and doesn't really have much benefit apart from being shorter and a bit more readable - just let me know in a reply and I'll approve.

2021-10-06 10:32 UTC, dezog approved these changes
Fine as it is

2021-10-06 10:37 UTC, merged