Added error 628
data-to-insight/csc-validator-be-903 pull request #322
Opened 2021-08-31 13:39 UTC by PhilDeakin

Added 628

2021-08-31 13:40 UTC, PhilDeakin commented
Clears issue 271

2021-09-01 08:03 UTC, mwaddoups requested changes
Similar to another rule we looked at I think - your solution works, but as this is an advanced rule a more readable solution exists using merging. In general if I've tagged something as advanced it's because I think it will need a merge or group by.

Happy for you to have a crack at this (by reading https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#database-style-dataframe-or-named-series-joining-merging first) - but ideally I think watching the new videos that should be coming out this morning should give a good primer.

Good work on getting to a workable solution with a bit more of a limited toolset though!

2021-09-01 08:03 UTC, mwaddoups commented on validator903/validators.py
> +            oc3_has_in_touch_activ_or_accom = oc3[(oc3['IN_TOUCH'].notna()) | (oc3['ACTIV'].notna()) | (oc3['ACCOM'].notna())]
A good trick for doing the mask in less space is
```
oc3[['IN_TOUCH', 'ACTIV', 'ACCOM']].notna().any(axis=1)
```

This
- `oc3[['IN_TOUCH', 'ACTIV', 'ACCOM']]` Selects just the appropriate columns.
- `.notna()` - returns a dataframe with the same columns and True/False values for nona
- `.any(axis=1)` - If any values are True, returns True. The `axis=1` specifies to work across rows rather than columns. This therefore aggregates the DataFrame to a Series.

2021-09-01 08:03 UTC, mwaddoups commented on validator903/validators.py
> +            child_in_header_in_oc3_with_appropriate_values = hea['CHILD'].isin(oc3_has_in_touch_activ_or_accom['CHILD'])
This one is tagged as an advanced rule - that tends to mean I'm looking for a merging or grouping solution. The video for this is coming out this morning so I would suggest looking through those materials before coming back to this.

Your solution using `.isin` will work, but will likely be orders of magnitude slower on the performance side - this is why merging tends to be preferred whenever we need to look across multiple tables.

In terms of approach, this is again one where the solution is complicated (you're good at picking these!). I think a good approach would be
- Inner merge oc3 and episodes on CHILD (this should be empty if there's no errors)
- Inner merge header with index column, (this will make sense once you watch the videos) with that output, which should give a list of error candidates.

2021-09-01 08:03 UTC, mwaddoups commented on validator903/validators.py
> +            child_in_header_in_oc3_with_appropriate_values = hea['CHILD'].isin(oc3_has_in_touch_activ_or_accom['CHILD'])
Actually - I will say that for smaller datasets (~1000-2000 children) the `isin` approach isn't much worse on performance, having just checked it. The merge will perform better as the datasets get larger.

I'd still suggest going for a merge with this anyway - the solution ends up being more readable, and it's a good opportunity to learn more about that side for other work you might do in Python!

2021-09-01 17:04 UTC, PhilDeakin commented on validator903/validators.py
> +            oc3_has_in_touch_activ_or_accom = oc3[(oc3['IN_TOUCH'].notna()) | (oc3['ACTIV'].notna()) | (oc3['ACCOM'].notna())]
Thanks.

2021-09-01 17:14 UTC, PhilDeakin commented on validator903/validators.py
> +            child_in_header_in_oc3_with_appropriate_values = hea['CHILD'].isin(oc3_has_in_touch_activ_or_accom['CHILD'])
I've changed this to merges... I played about with it, but I couldn't get the two the inner joins in your suggestion to work though, so it's a left join then inner join.

2021-09-02 07:34 UTC, mwaddoups requested changes
Nice one Phil, I like the solution you've used here and hopefully learning more about the merging was interesting too!

Fairly minor point here (and again more of a learning point than a functionality point) - but after that small change should be approved.

2021-09-02 07:34 UTC, mwaddoups commented on validator903/validators.py
> +            return {'Header': error_cohort['index'].to_list()}
I think you might get away with it here, but good practice is to get only the unique values from the index. Since you are merging header to episodes, the header index may get repeated.

In this particular case, I think OC3 and header will only have one entry per child but am not 100% sure, and because we only select children with no match they will only appear once.

However I'd suggest doing this anyway - it's a good habit to get into and avoids someone having to make the leap of faith. You can either `list(set(error_cohort['index']))` or `error_cohort['index'].unique().tolist()` I think.

2021-09-02 09:09 UTC, PhilDeakin commented on validator903/validators.py
> +            return {'Header': error_cohort['index'].to_list()}
Done, I've sorted it as well, probably not needed, but I doubt it's an expensive operation.

2021-09-02 10:55 UTC, mwaddoups commented on validator903/validators.py
> +            return {'Header': error_cohort['index'].to_list()}
Agree - it's not expensive. Cool - this looks good!

2021-09-02 10:55 UTC, mwaddoups approved these changes
Thanks for all the changes Phil, approved and in

2021-09-02 12:49 UTC, merged