Added validation rule 621.
data-to-insight/csc-validator-be-903 pull request #323
Opened 2021-08-31 14:47 UTC by jfan2006

Added validation rule 621.

Closes #267

2021-09-01 08:19 UTC, mwaddoups requested changes
Thanks for submitting this Fan.

Small bug here in converting to datetime - and you get a bit lucky (unlucky?) with your test cases that you don't spot it!

2021-09-01 08:19 UTC, mwaddoups commented on validator903/validators.py
> +            mask = (header['MC_DOB'] > header['DOB']) | header['MC_DOB'].isna()
Kind of a fun bug here - you need to convert these both to datetime first! Pandas allow this since comparison is defined for strings (e.g. `'b' > 'a') but that won't work for datetimes.

In general with dates you need to convert them, but also make sure you have the correct date format (d/M) and that you handle cases where a date is entered incorrectly without crashing (`errors='coerce'`). Otherwise use `pd.to_datetime` to make the conversion first. 

There should be examples of this in other errors you can look at.

2021-09-01 08:19 UTC, mwaddoups commented on tests/test_validators.py
> +        'MC_DOB': ['01/01/2021', '19/12/2016',  '31/01/19', pd.NA],
Might be worth adding a test case that checks the string conversion stuff - for example, '31/01/19' vs. '01/02/19' - the second one is a later date, but will show as less than the first in strings.

2021-09-21 14:00 UTC, dezog approved these changes
looks perfect, merging this

2021-09-27 16:42 UTC, dezog approved these changes

2021-09-27 16:43 UTC, merged