Added validation rule 612.
data-to-insight/csc-validator-be-903 pull request #324
Opened 2021-08-31 15:07 UTC by jfan2006

Added validation rule 612.

Closes #265

2021-09-01 11:35 UTC, dezog requested changes
Hi Fan,

This is looking to great, only a couple of small things that might be worth tweaking which I've noted as comments.

Other than that though, this is looking good to go! 👍

2021-09-01 11:35 UTC, dezog commented on validator903/validators.py
> +            mask = (header['MOTHER'].astype(str).isin(['0']) | header['MOTHER'].isna()) & header['SEX'].astype(str).isin(['2']) & header['MC_DOB'].isna()
A very minor style point - when there's only one value to check against, like `header['MOTHER'].astype(str).isin(['0']) `, I think it'd be a little more readable to just say `header['MOTHER'].astype(str) == '0'`

2021-09-01 11:35 UTC, dezog commented on tests/test_validators.py
> +        'MOTHER': ['0', '0', pd.NA, pd.NA],
One more test case would be good, just to ensure the error's not triggering when the child is in fact a mother. ie. when MOTHER = 1 and MC_DOB is valid

2021-09-20 09:02 UTC, jfan2006 commented
Hi @dezog made some changes but there are errors that I can't figure out.... could you help? thanks

2021-09-20 12:26 UTC, dezog commented
> 
> 
> Hi @dezog made some changes but there are errors that I can't figure out.... could you help? thanks

Hi Fan, sure thing - I'll give these all a proper look over tomorrow morning. 

At first glance I think this one might be down to needing extra brackets on the `mask =...` line

2021-09-21 12:11 UTC, dezog requested changes
Hey Fan, sorry for the delay. As I thought, the errors are being caused by one of those annoying syntax issues (stemming from my earlier suggestion - sorry about that!). I think I've also noticed a small bug in the validation logic.

2021-09-21 12:11 UTC, dezog commented on validator903/validators.py
> +            mask = (header['MOTHER'].astype(str) == '0' | header['MOTHER'].isna()) & header['SEX'].astype(str) == '2' & header['MC_DOB'].isna()
1. If I'm not mistaken, **`header['MC_DOB'].isna()` should be `header['MC_DOB'].notna()`, and the resulting mask should not then be negated as in line 19**, as this is then the correct code for the errors, and you only need to do that when you initially obtain the valid rows.
2. **This line needs brackets around `header['MOTHER'].astype(str) == '0'`, and around `header['SEX'].astype(str) == '2'`.**

    - This is because 'bitwise operators' like `|` and `&` happen before normal comparisons like `==`, so for example Python ends up trying to do `'0' | header['MOTHER'].isna()` first, which isn't what you want, and throws an error since '0' is a string not a bool (the error message `TypeError: Cannot perform 'or_' with a dtyped [bool] array and scalar of type [bool]` is kind of misleading...)

2021-11-13 13:50 UTC, dezog approved these changes

2021-11-13 13:50 UTC, merged