Added validation for error codes 153, 166, 174, 180, 181, 192, 193, 197
data-to-insight/csc-validator-be-903 pull request #340
Opened 2021-09-21 16:16 UTC by WMossDCC

Validation rules added for the above error codes.

Closes issues #40 #46 #51 #57 #58 #63 (+ duplicate #81 ?) #82 #84

2021-09-24 10:54 UTC, dezog requested changes
Great to see this come in. Excellent stuff and all very nicely laid out 👌 

Sorry for the delay in getting it back to you. 

I've put some comments throughout the code - the only definite issue's with rule 180, but it'd be great to get your point of view on the comments to rules 192 & 193, as the guidance document seems a bit ambiguous to me. 

Everything else is just small style/readability points: optional changes.

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            validation_error_mask = (~mask & ~na_location) | na_location
The logic works out correct here but could be simplified: `validation_error_mask = ~mask` by itself should catch all cases, as with `errors='coerce'`, `to_datetime` results in `pd.NA` for both blank and invalid values, so there's no need to differentiate between them
```
>>> test_values = ['', 'NULL', np.nan, pd.NaT, pd.NA, 20210401, '2021-04-01', '99/04/2021', '01/04/2021']

>>> pd.to_datetime(test_values, format='%d/%m/%Y', errors='coerce').isna()

array([ True,  True,  True,  True,  True,  True,  True,  True,  False])
```
This change is optional, but I think it's worth making for the readability of the code

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            mask = oc2['SDQ_SCORE'].astype(str).between('0','40')
This is the right idea (and really nice and concise!), but this one's actually a bit trickier than it seems.

First, we need to compare these as integers, because the way string comparisons happen with `>` and `<` is basically in terms of which comes first alphabetically, so as long as the first character is  between 0 & 3, the rest could be anything:
```
 >>> pd.Series(['041', '09999', '3~abc~XYZ']).between('0', '40').values

array([ True,  True,  True])
```
I think the best way would be to use `pd.to_numeric(oc2['SDQ_SCORE'], errors='coerce')`, as doing `.astype(int)` directly would cause an error if it found a value it couldn't convert to an integer. 

The other thing is that since the rule requires a whole number, we need to flag up values like `30.5`, which means the `.between` method isn't enough on its own. You could either combine that with checking that the decimal part of the number is 0, or check against the allowed values directly, by doing `.isin([0, 1, 2, 3, (...) , 40])`, or equivalently, `.isin(range(41))`

2021-09-24 10:54 UTC, dezog commented on tests/test_validators.py
> +        'SDQ_SCORE':    ['10', 41, '58', 72, '0', 40],
Adding few more exotic test cases would be good here, to catch the issues discussed in the comment on the validation check itself.

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            mask = header['SEX'].astype(str).isin(code_list)
optional change for conciseness - you could just simplify this to `mask = header['SEX'].astype(str) == '1'`

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
This appears correct according to the 'coding description', but the 'coding rule' is slightly contradictory and says this is supposed to checking if SUBSTANCE_MISUSE = 1 rather than if SUBSTANCE_MISUSE  is not blank. I'd tend toward the wording of the rule, "identified as having a substance misuse problem", what do you think?

![image](https://user-images.githubusercontent.com/63907524/134658014-7d1278da-9f26-4a2f-aeed-2f76248d4e31.png)
![image](https://user-images.githubusercontent.com/63907524/134659039-b3fef5ee-45a0-4a7d-99af-35cb76211337.png)

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
The code looks perfect but there's the same ambiguity as Rule 192. Again the coding description states "if <SUBSTANCE_MISUSE> is not provided then (...)"

I am also confused by the part where it says "Data is not accepted in either the intervention received or intervention offered fields once the substance misuse field is recorded as 0. " Any idea if that means you don't have to check for that because it's not possible (so only check if SUBSTANCE_MISUSE is blank), rather than that it should be flagged up as an error?

2021-09-24 10:54 UTC, dezog commented on validator903/validators.py
> +            validation_error_mask = ~score_na & ~reason_na
This is spot on. 

Extremely minor style comment - it'd be slightly easier to follow to use `.notna()`, and then not have to negate the two masks

2021-09-29 09:01 UTC, WMossDCC commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
Hi, thank you for the feedback! I think I've made the required changes.. apart from this one. I'm honestly not sure. I think what I've put covers the error rule for blank entries, but like you say if it's recorded as 0 then does it void the other 2 fields?

2021-09-29 10:42 UTC, SLornieCYC commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
Sorry, being nosy and looking at what everyone else is up to!

I think I'd expect 193 to work the same as discussed above for 192 and test whether <SUBSTANCE_MISUSE> = 0 rather than blank.

SUBSTANCE_MISUSE | INTERVENTION_RECEIVED | INTERVENTION_OFFERED | Outcome
----------------------- | ---------------------------- | ----------------------------- | ----------
0 | [null] | [null] | Correct
0 | [null] | 1 | Error
0 | 1 | [null] | Error
1 | [null] | [null] | Skip (Rule 192)
[null] | 1 | [null] | Skip (Rule 182)
[null] | [null] | 1 | Skip (Rule 182)

2021-09-29 16:16 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
Not at all @SLornieCYC , the more eyes on issues like these the better! 

I can't see the changes @WMossDCC , have you pushed the commits to the remote copy of the branch? 

I also still feel slightly uncertain because of the weirdly clashing descriptions, but but I don't think we'll be able to get a clearer answer til the gov portal opens to compare... I agree with Stephen that it makes the most sense to only test the cases where 
- `<SUBSTANCE_MISUSE> = 1` for Rule 192 (_INTERVENTION_RECEIVED must not be null_)
- those where `<SUBSTANCE_MISUSE> = 0` for Rule 193 (_INTERVENTION_RECEIVED & INTERVENTION_OFFERED must both be null_)
-  with `<SUBSTANCE_MISUSE> = [null]` being covered by Rule 182, which is:

    > If any of <IMMUNISATIONS>; <TEETH_CHECK>; <HEALTH_ASSESSMENT> or  <SUBSTANCE MISUSE> have not been provided, then none of <CONVICTED>; <HEALTH_CHECK>; <INTERVENTION_RECEIVED> or <INTERVENTION_OFFERED> should be provided

Good detective work Stephen - by the way, how did you insert a table in a reply??

2021-09-30 07:34 UTC, SLornieCYC commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
We can always contact DFE directly via their returns service desk and ask them to clarify the rule.  I've done that before outside the return period when I've spotted issues with the guidance.

Tables are written using markdown.  Not the quickest thing but okay for small tables: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

2021-10-01 10:17 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
That's neat, didn't know you could do that. Thanks for the tip

Contacting DFE's a good idea, I suspect we'll find more rules that are a bit ambiguous at some point. Any idea where you can access that returns service desk now? The form linked in page 3 of the validation checks doc seems to be gone
![image](https://user-images.githubusercontent.com/63907524/135457736-722f4957-0022-4a7d-87b9-c9e58073a897.png)

In the meantime, shall we stick with the above?

2021-10-01 11:27 UTC, SLornieCYC commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
I didn't even know that link was in the guide! 
Service desk is now here: https://form.education.gov.uk/service/Data-collections-service-request-form

2021-10-03 16:41 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
Sweet, thanks. I'll request some clarification on this and any other similar issues I can find this week. 

That sounds like it'd be useful to be hearing about - how does one get access to these bulletins?

2021-10-12 10:53 UTC, SLornieCYC commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
FYI that updated guidance has been published: [Children looked after return 2021 to 2022: technical specifications](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications)

Coincidentally one of the three changed rules is included in this PR! (197 renamed to 197a)

2021-10-21 07:35 UTC, dezog commented on validator903/validators.py
> +            misuse_na = oc2['SUBSTANCE_MISUSE'].isna()
Ah, great, thanks for adding these in! Unfortunately the ones that were confusing us haven't been updated 😅

2021-11-11 20:59 UTC, merged