Added validator for error rule 207.
data-to-insight/csc-validator-be-903 pull request #366
Opened 2021-10-27 10:08 UTC by SLornieCYC

Closes #114

2021-11-02 19:51 UTC, dezog requested changes
Textbook as usual except for a big: this one's a bit different to the rest of this little batch in that it can in fact change, but only in one direction - further comment in code

2021-11-02 19:51 UTC, dezog commented on validator903/validators.py
> +            mother_is_different = header_merged['MOTHER'].astype(str) != header_merged['MOTHER_last'].astype(str)
this just should be checking that if it was 1 last year it's 1 this year too

2021-11-03 09:42 UTC, SLornieCYC commented on validator903/validators.py
> +            mother_is_different = header_merged['MOTHER'].astype(str) != header_merged['MOTHER_last'].astype(str)
Oops! Now fixed.

2021-11-12 12:29 UTC, dezog approved these changes
perfect, cheers Stephen!

2021-11-12 12:45 UTC, merged