demonstrate functionality of solving error 552
data-to-insight/csc-validator-be-903 pull request #381
Opened 2021-11-05 10:20 UTC by tab1tha

Added rule 552

Closes #235

2021-11-05 16:57 UTC, dezog requested changes
Hey Tambe, 

this is really close to done now - still a couple of changes to make; see the comments below.

This was a really difficult and confusing rule to start off with, so well done for getting it into shape

2021-11-05 16:57 UTC, dezog commented on tests/test_validators.py
> +    'DATE_PLACED':['08/03/2020','22/06/2020','13/10/2022','24/10/2021'],
What happened to the tests we had added including missing values? 

Currently, if the user loads a file with missing values in DATE_PLACED or DECOM this function will break, so we need to put it back to how it was in https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/381/commits/4dcbfa8cfd03a369ea62ff48c7f0d4365a06fa83, and add the changes to validators.py (see other comment)

2021-11-05 16:57 UTC, dezog commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
We need to remove the rows of `placed_adoption` where `DATE_PLACED.isna()` before this line, to stop idxmax running into problems

2021-11-05 16:57 UTC, dezog commented on validator903/validators.py
> +      adoption_eps_inds = adoption_eps.groupby('CHILD')['DECOM'].idxmin(skipna=True)
Like above, we should also remove the rows of `adoption_eps` where DECOM's a NaN

2021-11-05 16:57 UTC, dezog commented on poetry.lock
any idea what happened here? did you update the package versions in the poetry file somehow?

2021-11-08 14:02 UTC, tab1tha commented on poetry.lock
I have no idea yet.

2021-11-08 14:02 UTC, tab1tha commented on validator903/validators.py
> +      adoption_eps_inds = adoption_eps.groupby('CHILD')['DECOM'].idxmin(skipna=True)
Done

2021-11-08 14:02 UTC, tab1tha commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
Done

2021-11-08 14:03 UTC, tab1tha commented on tests/test_validators.py
> +    'DATE_PLACED':['08/03/2020','22/06/2020','13/10/2022','24/10/2021'],
Done

2021-11-08 14:24 UTC, dezog requested changes
Nice work, just one more tiny fix to make!

2021-11-08 14:24 UTC, dezog commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
Thanks for putting these in, it's working fine for our test cases, but I've noticed a bug:

    placed_adoption = dfs['PlacedAdoption'].dropna()

will drop the rows where *any* column contains a NaN, so it'd be better to do:
```
placed_adoption = dfs['PlacedAdoption'].dropna(subset='DATE_PLACED')
```
and likewise add `subset='DECOM'`  for episodes

2021-11-08 15:16 UTC, tab1tha commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
using subset did not produce the required results. This worked instead: https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-a-certain-column-is-nan

2021-11-08 16:27 UTC, dezog commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
Completely my bad, sorry about that - the subset needs to be a list, e.g. `placed_adoption.dropna(subset=['DATE_PLACED'])`

2021-11-08 18:39 UTC, tab1tha commented on validator903/validators.py
> +      placed_adoption_inds = placed_adoption.groupby("CHILD")["DATE_PLACED"].idxmax(skipna=True)
Would you like me to change it back to this instead?

2021-11-12 10:47 UTC, dezog approved these changes

2021-11-12 17:08 UTC, merged