Added 370,371,372,373,374,375,376,379
data-to-insight/csc-validator-be-903 pull request #384
Opened 2021-11-08 13:54 UTC by PhilDeakin

Added 370, 371, 372, 373, 374, 375, 376, 379

2021-11-08 14:15 UTC, PhilDeakin commented on validator903/validators.py
> +            if subval == '370' or subval == '371' or subval == '372' or subval == '373' or subval == '374':
I presume there's an "isin" function or something equivalent to do this, but I got bored looking for it.

2021-11-09 16:24 UTC, PhilDeakin commented on validator903/validators.py
> +            if subval == '370' or subval == '371' or subval == '372' or subval == '373' or subval == '374':
Amended

2021-11-09 19:40 UTC, dezog reviewed
Nice work again! Almost two whole 'packs' from the spreadsheet in one commit 🤯 

![image](https://user-images.githubusercontent.com/63907524/140992937-e0891894-2711-4066-95d3-7828153ecec0.png)

Only one necessary change I can see - adding a dropna before comparing the values, check out the comment below

2021-11-09 19:40 UTC, dezog commented on validator903/validators.py
> +                pd.offsets.DateOffset(years=Gen_370_dict[subval]['Y_gap']))
Optional change: for style, better to indent this line so it's obvious it's a continuation of the previous one

2021-11-09 19:40 UTC, dezog commented on validator903/validators.py
> +            if subval in  ['370', '371', '372', '373', '374']:
Yep, well done!

2021-11-09 19:40 UTC, dezog commented on validator903/validators.py
> +            merged_e = epi_p2.merge(hea, how='inner', on='CHILD')
At this point, I think we should do `merged_e = merged_e.dropna(subset=['DECOM', 'DEC', 'DOB'])`, so this error doesn't trigger where there are missing/invalid values. Does that make sense?

2021-11-09 19:40 UTC, dezog commented on tests/test_validators.py
> +        'CHILD': ['111', '222', '333', '444', '555', '666'],
Optional change: add pd.NA values to the tests to make sure that's working as expected.

2021-11-10 11:32 UTC, PhilDeakin commented on validator903/validators.py
> +                pd.offsets.DateOffset(years=Gen_370_dict[subval]['Y_gap']))
Changed

2021-11-10 11:32 UTC, PhilDeakin commented on validator903/validators.py
> +            merged_e = epi_p2.merge(hea, how='inner', on='CHILD')
Added

2021-11-10 11:32 UTC, PhilDeakin commented on tests/test_validators.py
> +        'CHILD': ['111', '222', '333', '444', '555', '666'],
Added a few.

2021-11-10 14:59 UTC, dezog approved these changes
Fantastic, all present & correct - merging this now 🙂

2021-11-10 15:12 UTC, dezog requested changes
Sorry, I missed something - looks like the dropna line didnt make the commit, please could you double check that one?

2021-11-10 15:12 UTC, dezog commented on validator903/validators.py
> +            merged_e = epi_p2.merge(hea, how='inner', on='CHILD')
I don't think this change made it in

2021-11-10 15:19 UTC, PhilDeakin commented
Corrected now... (I hope) @dezog

2021-11-11 19:17 UTC, dezog approved these changes
Awesome, cheers Phil! As per earlier email, in future I'll tend to just make quick little tweaks like this myself, and just leave a comment if it's something that'd be useful to bear in mind going forward

2021-11-11 19:27 UTC, merged