Added 442
data-to-insight/csc-validator-be-903 pull request #439
Opened 2021-11-22 17:17 UTC by tab1tha

Added 442

Closes #200

2021-11-22 18:11 UTC, dezog requested changes
Hey Tambe, please see comment below

2021-11-22 18:11 UTC, dezog commented on validator903/validators.py
> +      episode_error_locs = merged.loc[mask, 'index_eps']
This is failing because it's returning [nan, 4] instead of [0, 4] for the header errors, since some rows of `index_er` will have missing values due to the left merge. 

Another consideration is that children with multiple episodes will currently get an error on their header entry for every episode. 

The easiest thing would be to do .dropna and .unique on the `header_error_locs`

2021-11-23 15:41 UTC, tab1tha commented on validator903/validators.py
> +      episode_error_locs = merged.loc[mask, 'index_eps']
Done. 
I have also pushed a last commit that makes the .dropna() unnecessary. The nan was raised because I mistakenly put the CHILD ID as NaN instead of the variable itself. Thank you.

2021-11-23 18:12 UTC, dezog approved these changes
Added the dropna, otherwise great!

2021-11-23 18:12 UTC, dezog commented on validator903/validators.py
> +      episode_error_locs = merged.loc[mask, 'index_eps']
The dropna will still be necessary, as someone might upload data with episodes for a child who is not in the Header -- those rows in `merge` will end up giving us nan's in the Episodes errors

2021-11-23 18:12 UTC, dezog commented on validator903/validators.py
> +      episode_error_locs = merged.loc[mask, 'index_eps']
I've changed this and merged

2021-11-23 18:12 UTC, merged