Added 632
data-to-insight/csc-validator-be-903 pull request #522
Opened 2021-12-13 16:11 UTC by tab1tha

Added 632

Closes #274

2021-12-15 14:10 UTC, dezog requested changes
Yikes, this is one of those surprisingly tricky rules, took a lot of figuring out to get my head around how to do it. I've added a few comments in the code, but overall I think the process should be changed a bit to the following, so that it's possible to check partially complete dates like 'zz/zz/2003' against the DECOM:

1. `DATE_PERM_dt = DATE_PERM.apply(valid_date)` (see new version below)
2. drop all episodes except each child's first
3. `mask = ((DATE_PERM_dt > DECOM) | DATE_PERM_dt.isna()) & (DATE_PERM != 'zz/zz/zzzz') `
    - if DATE_PERM_dt is after first DECOM it's an error (should be before)
    - If DATE_PERM_dt is null, it's an error (wrongly formatted date)
    - unless DATE_PERM is 'zz/zz/zzz', then it's valid (cant do date comparison)
---
Instead of returning True/False, `valid_date` now converts the string to a datetime if possible. 'zz/zz/zzzz' results in NaT, so we have to check for that in 3. above
```
def valid_date(dte):
    lst = dte.split('/')
    
    if len(lst) != 3:
        return pd.NaT

    z_list = ['zz', 'zz', 'zzzz']
    # We set the date to the latest possible value to avoid false positives
    offset_list = [pd.DateOffset(months=1, days=-1),
                   pd.DateOffset(years=1, days=-1),
                   None]
    already_found_non_zeds = False
    date_bits = []

    for i, zeds, offset in zip(lst, z_list, offset_list):
        if i == zeds:
            # I'm assuming it is invalid to have a date like '01/zz/zzzz'
            if already_found_non_zeds:
                return pd.NaT
            # Replace day & month zeds with '01' so we can check if the resulting date is valid
            # and set the offset so we can compare the latest corresponding date
            elif i == 'zz':
                i = '01'
                offset_to_use = offset
        else:
            already_found_non_zeds = True
        date_bits.append(i)
    
    as_datetime = pd.to_datetime('/'.join(date_bits), 
                                 format='%d/%m/%Y', errors='coerce')
    try:
        as_datetime += offset_to_use
    except NameError:  # offset_to_use only defined if needed
        pass  
    return as_datetime  

```

2021-12-15 14:10 UTC, dezog commented on validator903/validators.py
> +          lst = dte.split("/")
the split method doesnt raise an error if the separator isn't found, it just returns a list of length 1 with the entire string. it'd be better to get rid of this try/except and use len:
```
if len(dte.split("/")) != 3:
    return False
```

In general it's not ideal to wrap everything in a try/except unless you're catching a specific error and know what will cause it. Otherwise it can hide any bugs that take place within the `try` and make it hard to figure out what's up.

2021-12-15 14:10 UTC, dezog commented on validator903/validators.py
> +              if not 'zz' in i.lower():
this should be `if i.lower() != 'zz':`

otherwise e.g. '19zz' or '2zzbhvv;' would end up counting as valid

I see what you were going for as it looks like the year requires four z's. Unfortunately we'll have to be explicit about it, I think the best we can do is change the loop to: 

```
z_list = ['zz', 'zz', 'zzzz']
for i, zeds in zip(lst, z_list):
    if i != zeds:
        # ...

2021-12-15 14:10 UTC, dezog commented on validator903/validators.py
> +                return True
don't return True yet, as this will only ever do one pass through the loop - omit this else block

2021-12-15 14:10 UTC, dezog commented on validator903/validators.py
> +      mask = merged['DATE_PERM'].apply(valid_date)
the `valid_date` function assumes it's being passed a string (by relying on the .split method) - this will cause an AttributeError, which is currently getting caught by the generic `except`

2021-12-15 14:10 UTC, dezog commented on tests/test_validators.py
> +      'DATE_PERM': ['xx/10/2011', '17/06/2001', '01/05/2000', pd.NA, '05/zz/2020'],
I would add a couple extra checks for DATE_PERM values:
'zz/zz/1993' - valid
'zz/zz/zzzz' - valid
'zz/zz/zz' - fail (I think - wrong zeds)
'01/13/2000' - fail (bad month)
'01/zz/2000' - fail (zeds followed by not-zeds)

2021-12-15 16:56 UTC, tab1tha commented on validator903/validators.py
> +              if not 'zz' in i.lower():
here I was considering the possibility of checking for both zz and zzzz (placeholder for year). I see your point though.

2021-12-16 15:44 UTC, dezog approved these changes
Everything looks good, great work Tambe. Just made one tweak so it only triggers if DATE_PERM's invalid, but not if it's missing since this is one of those 'if provided...' ones

2021-12-16 15:44 UTC, merged

2021-12-16 15:59 UTC, tab1tha commented
> Everything looks good, great work Tambe. Just made one tweak so it only triggers if DATE_PERM's invalid, but not if it's missing since this is one of those 'if provided...' ones

I see. I included that because the NaNs where causing an AttributeError at the .split() line.