poc manage registry within package of year rules
data-to-insight/csc-validator-be-903 pull request #648
Opened 2023-06-09 10:44 UTC by tab1tha

2023-06-09 16:09 UTC, franciscobmacedo approved these changes
I think it looks ok, but I would strongly advise not to do that registry loop "live", as in, when the users are using the app/CLI. It should run only once a new rule is added and stored somewhere I think

2023-06-09 16:09 UTC, franciscobmacedo commented on lac_validator/rules/lac2022_23/__init__.py
> +
a few things here:

1 - No need to have so many loops/list comprehension (I count 4 instead of 2 that are really needed).
2 - I don't like variables called "p" or "n" even if they are in a list comprehension: Why not just call them what they are? 
2 I would suggest, for the sake of cleaning the code, for this to be a function, so:

```python
def get_registry():
    for path in Path(__file__).parent.glob("*.py"):
        if path.stem == "__init__":
            continue
        rule_content = importlib.import_module(f"lac_validator.rules.lac2022_23.{path.stem}")
        for name in dir(rule_content):
            element = getattr(rule_content, name)
            if validator_function := getattr(element, "rule", None):
                registry.append(validator_function)
            
    
registry = get_registry()
```

I didn't test this code, so some adaptation might be needed

2023-06-09 16:09 UTC, franciscobmacedo commented on rpc_main.py
> +    ruleset_registry = getattr(module, "registry")
No need to use `getattr`in here I think you can just do `ruleset_registry = module.registry`

2023-06-09 16:09 UTC, franciscobmacedo commented on lac_validator/rules/lac2022_23/__init__.py
> +
Also, I'm not sure what kaj suggested, but this is quite an expensive piece of code, it takes some time. I wonder if it wouldn't make sense just to call this function on a github action and dump the registry list in a json/yml file? And then you can just load that when you need it? It's far less expensive to load a file than it is to loop through each file every time a user wants to use the tool.

You can make the github workflow run on every merge.

This is a suggestion that you can add to the tasklist if you find it relevant, not at all for you to do know.

2023-06-12 08:37 UTC, cyramic reviewed
I ran this through `pylint` and `black` modules, and there are a lot of suggested changes I think should be required before a merge so that the code meet things like PEP8 and readability standards.

2023-06-12 08:58 UTC, cyramic requested changes

2023-06-12 08:58 UTC, cyramic commented on lac_validator/__main__.py
>      print(f"*****************Error report******************")
Is there a reason we're outputting to console (print) instead of using a logger that would give more options? Or are these here for more debugging reasons?

2023-06-12 08:58 UTC, cyramic commented on lac_validator/lac_validator_class.py
>  # TODO rename this file
Is this "TODO" tech debt? What is the purpose of this note here?

2023-06-12 08:58 UTC, cyramic commented on lac_validator/lac_validator_class.py
>  # TODO rename this file
If it is really something that needs to be done, a way to make sure it doesn't get lost is to put it in the issue tracker and not as a comment here where it could potentially be forgotten. Try not to put things like this in code. In the issue tracker, you can link to the file or line that you feel needs a fix in the future.

2023-06-12 08:58 UTC, cyramic commented on lac_validator/rules/lac2022_23/__init__.py
> +
I second Francisco's suggestion above. I also feel that this code isn't very easily testable as written, is it?  I also wonder if we should put a try/except block around the import_module function to catch if an import fails, but I'm not sure how necessary that is.

2023-06-12 08:58 UTC, cyramic commented on rpc_main.py
> +    ruleset_registry = getattr(module, "registry")
It depends on if that value is potentially nonexistant. If we're sure it always exists, I'd say go with the dot notation, otherwise this way could catch errors more easily.

2023-06-12 08:58 UTC, cyramic commented on rpc_main.py
> +    ruleset_registry = getattr(module, "registry")
These two lines are a repeat of the lines 32,33 above. It might be a good idea to move this to a separate function so you're not repeating yourself and then having to rewrite multiple sections of code if we decide to change in the future.

For instance, if we want to add more error-handling and security checks on the import module step or if there's a bug. Ideally we'd like to do this in one place instead of several.

2023-06-19 11:05 UTC, franciscobmacedo commented
> I ran this through `pylint` and `black` modules, and there are a lot of suggested changes I think should be required before a merge so that the code meet things like PEP8 and readability standards.

this is not the final PR of the refactoring - that should be another one. Note that the destination branch is not the main one.

2023-06-19 11:06 UTC, franciscobmacedo commented on lac_validator/lac_validator_class.py
>  # TODO rename this file
Tambe didn't have the time to do it - so we left it in the code. I agree, we should add a few issues to this, including the tasks in the main comment.

2023-07-06 10:37 UTC, merged