Adds ingress for combined SCP and CH lists
data-to-insight/csc-validator-be-903 pull request #711
Opened 2023-10-30 13:13 UTC by WillLP-code

Adds the ability to check uploads to the FE so the new, combined SCP/CH list can be uploaded.
Assumes people will use what is currently the CH box to upload the combined list (fe changes to come later).
Adds a function to check what's in the upload, adds a function to create the providers list for the metadata for a single list (built on the original providers metadata function) and adds relevant tests.

2023-11-01 12:15 UTC, SLornieCYC commented on lac_validator/ingress.py
> +            )
~~Do these two `UploadError` messages need updating to reference the fact that newer lists come in a single file?~~ EDIT: Nevermind, I've seen you're handling that in the new `combined_ch_scp_check` function at line 708!

2023-11-01 12:15 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    logger.info(f"CH dataframe complete. Creating SCP dataframe {sc.t}")
Is this long section still required for retrieving data from the new single Ofsted file?  

The try except set-up was added for the two separate files due to an incremental change in one of the templates ([details here](https://github.com/data-to-insight/csc-validator-be-903/issues/606)) but I would hope that for the new file we wouldn't need that? Unless Ofsted have already started fiddling with the structure of the new file!

2023-11-02 09:22 UTC, WillLP-code commented on lac_validator/ingress.py
> +    logger.info(f"CH dataframe complete. Creating SCP dataframe {sc.t}")
You're right, I just didn't know if different LAs had different headings so I pretty much just took the original two file function and re-worked it for the single file, so I'll hop back in and simplify this!

2023-11-02 10:25 UTC, WillLP-code commented on lac_validator/ingress.py
> +    logger.info(f"CH dataframe complete. Creating SCP dataframe {sc.t}")
So I've removed the first try/except, but I've kept the second one because it's an important error to raise

2023-11-02 11:31 UTC, SLornieCYC requested changes

2023-11-02 11:31 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    # check whether file includes consolidated provider information sheet
This comment not required (not relevant to the new single file and doesn't reflect subsequent code).

2023-11-02 11:31 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    scpch_address = scpch_providers[["urn", "setting address postcode"]]
This line not required (not relevant to the new single file and not actually being used anyway).

2023-11-02 11:31 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    del scpch_providers, scpch_address
After removing line 441 above (see separate comment) `scpch_address` can be removed here too.

2023-11-02 11:31 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    # if not check whether file includes separate setting and address sheets
This comment not required (not relevant to the new single file and doesn't reflect subsequent code).

2023-11-02 11:31 UTC, SLornieCYC commented on lac_validator/ingress.py
> +    logger.info(f"CH dataframe complete. Creating SCP dataframe {sc.t}")
Great, that looks much neater!

2023-11-09 14:21 UTC, SLornieCYC approved these changes

2023-11-10 08:19 UTC, merged