Rule584
data-to-insight/csc-validator-be-903 pull request #720
Opened 2023-11-07 15:26 UTC by WillLP-code

closes #618 

Rule logic: fail rows where date_placed_current is earlier than date _placed_last in instances where there is no _reason_placed_ceased, and where there is a date_placed_last, also fails rows where current date_placed is empty, but date_placed_last is not, and date_placed_ceased and reason_placed_ceased are not

2023-12-08 11:10 UTC, SLornieCYC requested changes

2023-12-08 11:10 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +        ]
This filter is on the wrong dataframe.  We want to check **all** of the current year records against **the subset of the previous year** that were not ceased (date or reason).  Change `df` to `pa_last` and I think we're good for this part.

2023-12-08 11:10 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +        df_merged = df_merged[df_merged["DATE_PLACED_last"].notna()]
I think this is fine; but is there a benefit to dropping the nil-last-year rows by filtering after the merge like this, rather than making the merge `inner` instead of `left`?

2023-12-08 11:10 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +                df_merged["DATE_PLACED_current"] < df_merged["DATE_PLACED_last"]
Think this needs to be `<=` rather than just `<` so we capture those in the current year that have the same start date as an ended decision in the previous year.

2023-12-08 11:26 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +    message="If the date of the decision that the child should be placed for adoption in the current year is different to the date of the decision recorded in a previous year, then the decision to pl
Usually we've included the shorter error description as that matches what is shown to users in the DFE portal.

2023-12-11 14:30 UTC, WillLP-code reviewed
@SLornieCYC I think that's everything you've asked for!

2023-12-12 14:12 UTC, SLornieCYC requested changes

2023-12-12 14:12 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +            },  # 1 Fail, test DPC null
I think the null `DPC` should be on the previous year record now for this test?

2023-12-12 14:12 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +            },  # 2 Fail, test RPC null
I think the null `RPC` should be on the previous year record now for this test?

2023-12-12 14:12 UTC, SLornieCYC commented on lac_validator/rules/lac2022_23/rule_584.py
> +            },  # 3 Pass
This record fails now so comment is wrong.  Unless the intent is to test null for both `DEC` **and** `RPC` in which case those nulls should be on the previous year record now.

2023-12-21 09:11 UTC, SLornieCYC approved these changes
Think this looks right now.

2024-01-02 08:51 UTC, merged