1016 working
data-to-insight/csc-validator-be-903 pull request #721
Opened 2023-11-08 10:19 UTC by WillLP-code

closes #693 

Adds 1016 to 23/24
Uses np.timedeltas to calculate ages, which I think is fine, but I don't know if there's some obscure reason where it may not catch edge cases say if someone has been alive for 19 years but somehow isn't 19, or something, I'm not sure if there was a standard way of doing it for the validator I'm not aware of.

2023-11-09 14:50 UTC, SLornieCYC commented
Can't see any problem with using np.timedeltas.  I think most of the previous implementations around age have used pd.offsets.DateOffset - for example rule 1007 which is very similar to this one. (No I don't know why DFE have written the validation rules this way; I'm sure it makes sense to them!).

https://github.com/data-to-insight/csc-validator-be-903/blob/77d4908cd90792ecb77dea9884c6ef49eefa032b/lac_validator/rules/lac2022_23/rule_1007.py#L33-L38

2023-11-09 14:54 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    metadata = {"collection_end": pd.to_datetime("01/01/2020", format="%d/%m/%Y")}
Doesn't this need to be in the main `validate()` function? I don't think the dataframes from ingress are converted due to some weird bit in the DFE specification for partial/unknown dates.

2023-11-10 09:37 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    metadata = {"collection_end": pd.to_datetime("01/01/2020", format="%d/%m/%Y")}
I actually didn't know ingress didn't convert to datetimes, I think there's a bunch of times I'll need to fix this then!

2023-11-10 09:44 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    metadata = {"collection_end": pd.to_datetime("01/01/2020", format="%d/%m/%Y")}
See this comment on a previous issue:  https://github.com/data-to-insight/csc-validator-be-903/issues/654#issuecomment-1679033062.  Although I have no clue how (or if) DFE validate such data through the rest of the date-based rules (I think we've just accepted we're ignoring partial dates in this tool!).

2023-12-08 11:23 UTC, SLornieCYC requested changes
This needs to include a check against the Episodes file to determine whether the child left care after their in-year birthday.  (We only want to flag those who have OC3 data **and** their last Episodes `DEC` was **after** their 17th or 18th birthday).

2023-12-11 15:20 UTC, WillLP-code reviewed
@SLornieCYC I've had a look at this but I might need to look again tomorrow. I don't know how I missed the DEC part of the rule in my original attempt!

2023-12-21 09:32 UTC, SLornieCYC requested changes

2023-12-21 09:32 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    else:
This needs to be `or` rather than `&`.

2023-12-21 09:32 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +        df_merged = OC3.merge(episodes, on="CHILD", how="left")
_Think_ this can be an inner join because we only care about OC3 records who have episodes in current year.  (They could be 17-18yrs and have left care in previous year and therefore have no episodes this year).

2023-12-21 09:32 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            & (df_merged["DEC"] >= (df_merged["DOB"] + np.timedelta64(17, "Y")))
The last filter here needs to accommodate 17th **_or 18th_** birthday as it could be either of these.

2024-01-03 09:41 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            & (df_merged["DEC"] >= (df_merged["DOB"] + np.timedelta64(17, "Y")))
So, I could be wrong, but what I've done is take anyone who is between 17 and 19 and who has a DEC after their 17th birthday, so that will include children who have had their 17th or 18th birthdays. Wouldn't adding a check for those who have a DEC after their 18th birthday be redundant?

2024-01-04 11:33 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            & (df_merged["DEC"] >= (df_merged["DOB"] + np.timedelta64(17, "Y")))
The key thing here is that they need to have left care on or after **the in-year birthday** to flag on this rule.

For example:

- Child turned 18 on 1 September
- Child left care on 31 August (before birthday)

At the moment this case will return **true**, **true**, **true** for the filter (fail) because the last part checks the 17th birthday only, whereas we actually want the third part to be checking their 18th birthday because they are turning 18 during the year (and which should return false).

[`AGE_AT_CE` < 19, `AGE_AT_CE` >= 17, **`DEC` >= 17th birthday**] 

Here are some other examples that I think should pass (any false) or fail (all criteria true):

### Pass
- Child turned 17 on 1 September
- Child left care on 31 August (before birthday)

### Fail
- Child turned 17 on 1 September
- Child left care on 2 September (after in-year birthday)

### Fail
- Child turned 18 on 1 September
- Child left care on 2 September (after in-year birthday)

2024-02-26 14:29 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            & (df_merged["DEC"] >= (df_merged["DOB"] + np.timedelta64(17, "Y")))
If I am right in my interpretation of the above, the latest commit should pass and fail according to the above.

2024-02-29 09:55 UTC, SLornieCYC requested changes

2024-02-29 09:55 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            {"CHILD": "child8", "DEC": "31/08/20020"},
Typo in year; think this should be 2020?

2024-02-29 09:55 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +            {"CHILD": "child10", "DEC": "02/09/2020"},
On second thought I think the dates used for these three tests make this a bit harder to comprehend because you've set `collection_end` = 31/03/2020 and then using `DEC` after that.  I'd suggest making the `DEC` 2019 (so within the same return year as `collection_end`) and adjust the DOBs accordingly.

2024-02-29 09:55 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
>          ]
This looks better to me but I think it needs to be structured like this to avoid `condition_17` applying when the child turns 18 duing the year.  But with however many extra brackets python needs for that expression.

`AGE_AT_CE` >= 17 & `AGE_AT_CE` < 18 & `condition_17` |  `AGE_AT_CE` >= 18 & `AGE_AT_CE` < 19 & `condition_18`

2024-02-29 09:55 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    assert result == {"OC3": [0, 3, 8, 9]}
As covered in above comment about `condition_17` I think some of these may be false-positives due to turning 18 but the logic is currently seeing `DEC` > 17.

2024-03-05 14:54 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    assert result == {"OC3": [0, 3, 8, 9]}
So, I've made explicit in the comments where I think rows should pass and fail based on my understanding of the rule. I've also had to change the condition 17/18 to use pandas date offsets because for some periods being having a dec the same date 18 years after a DOB didn't count as the right number of years because no.timedelta has years as exactly 365 86,400s days, so for some periods leap seconds messed up calculations (namely child 4 with a DOB of 01/01/2002 and a dec of 01/01/2020 was passing when they should fail as they're 18 ON their DEC)

2024-03-12 14:29 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_1016.py
> +    assert result == {"OC3": [0, 3, 8, 9]}
Thanks Will; I think this one looks right to me now too.  I've pushed some amendments to the tests.

2024-03-12 14:29 UTC, SLornieCYC approved these changes

2024-04-16 08:15 UTC, merged