347 working
data-to-insight/csc-validator-be-903 pull request #722
Opened 2023-11-08 11:02 UTC by WillLP-code

closes #694 

Fails children under 18 with an ACCOM in OC3 of T

2023-11-09 15:01 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +    message="Only care leavers aged 18 years or over can be accommodated in a Foyer or similar accommodation. Check if the accommodation should be reported instead as ‘D’ (registered supported accomm
Usually we've included the shorter error description as that matches what is shown to users in the DFE portal.

2023-11-09 15:03 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +        collection_end = dfs["metadata"]["collection_start"]
Not at all confusing naming! :P

2023-11-09 15:04 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +        df["AGE_AT_CE"] = collection_end - df["DOB"]
You'll need to convert this to a date as will come in from DF as a string.

2023-11-10 09:48 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_347.py
> +        collection_end = dfs["metadata"]["collection_start"]
I had just copy pasted old code and not changed it... oops

2023-12-08 11:36 UTC, SLornieCYC requested changes

2023-12-08 11:36 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +        df["AGE_AT_CE"] = collection_start - df["DOB"]
Should this new column be `AGE_AT_CS` given this rule is using `collection_start`?

2023-12-08 11:36 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +    metadata = {"collection_start": pd.to_datetime("01/01/2020", format="%d/%m/%Y")}
It might be better to have the `collection_start` match what we use in the return (i.e. 1 April rather than January).

2023-12-08 11:36 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_347.py
> +            },  # Fail, under 18, accom = T
Should this fail? DOB 01/01/2002 and collection_start 01/01/2020 would make it the day of their 18th birthday?

2023-12-12 13:51 UTC, SLornieCYC approved these changes
Looks good to me!

2023-12-12 13:53 UTC, merged