222 ammended for 23/24 return with test
data-to-insight/csc-validator-be-903 pull request #725
Opened 2023-11-08 13:30 UTC by WillLP-code

closes #698

2023-12-08 13:36 UTC, SLornieCYC requested changes
This change is fine apart from one redundant line - and the fact that it needs to be added in the **2024/25** year!  (Rather than amended in 2023/24 when P2 is still a valid code)

2023-12-08 13:36 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_222.py
> +            {"PLACE": "P2", "URN": "Whatever"},  # 6  Pass
This line isn't needed because this rule change is due to P2 ceasing to be a valid code **at all** in 2024/25; all we're doing is updating the rule to remove the reference to a now redundant item.  (Checking whether used `PLACE` codes are valid is handled by another rule).

2023-12-12 09:41 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_222.py
> +            {"PLACE": "P2", "URN": "Whatever"},  # 6  Pass
I'll do this when the 218 change is merged to main so I can merge main back into this branch, and avoid making the 24/25 folder and init in multiple branches and risking conflicts!

2023-12-12 15:33 UTC, SLornieCYC approved these changes
Think this is good now!

2023-12-12 15:38 UTC, merged