371 ammended Place code K3, age 16
data-to-insight/csc-validator-be-903 pull request #726
Opened 2023-11-08 13:40 UTC by WillLP-code

closes #699 
Updates 371 for 23/24 by changing code to K3 from H5 and updating age from 14 to 16

2023-12-08 13:47 UTC, SLornieCYC requested changes
This one is fine, apart from the change comes in from the **2024/2025** return (not 2023/2024) so the rule file needs moving forward a year in the folder structure.

2023-12-08 13:47 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_371.py
> +            "PLACE": ["K3", "P2", "P2", "K3", "K3", "K3"],  # 14bd    #day before 14bd
Comment needs updating to 16bd.

2023-12-12 09:42 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_371.py
> +            "PLACE": ["K3", "P2", "P2", "K3", "K3", "K3"],  # 14bd    #day before 14bd
As with 222, I'll do this when 218 is merged in as it has the folder/init structure for 24/25 :)

2023-12-12 15:34 UTC, SLornieCYC approved these changes
Think this one is good now!

2023-12-12 15:39 UTC, merged