SW01STG1
data-to-insight/csc-validator-be-903 pull request #739
Opened 2023-12-13 14:41 UTC by WillLP-code

closes #669 

> DfE Long-form description of error
> If the child is looked after on 31 March then social worker episodes data should be reported for the child.
> Check that social worker ID, team and episode start and end dates have all been entered.
> 
> DfE suggested coding
> If <CLA_AT_31_MARCH> then at least one instance of each of the following items should be provided: <SW_ID>, <SW_DECOM>, <SW_REASON>

I'm, once again, not convinced that the suggested coding and the long form description mean the same thing, but this is coded according to the DfE coding.

Logic: if a child passes the criteria to be looked after 31 march, they need to have at least one of each of ID, DECOM, and REASON (meaning they need to have all three because of the 'each of')

2023-12-20 08:22 UTC, WillLP-code commented
now additionally closes #701

2023-12-21 10:41 UTC, SLornieCYC commented
> 
> I'm, once again, not convinced that the suggested coding and the long form description mean the same thing, but this is coded according to the DfE coding.

I think the long form description is slightly outdated due to amendments to both the collection and the rule.  Worker team was something in the original proposed spec for the module but dropped before the guidance was issued.  End date was in the original rule coding for 2023/24 but then dropped in the v1.2 revision.

2023-12-21 10:41 UTC, SLornieCYC commented
> now additionally closes #701

Is there a commit you've not pushed for this addition?  The second issue is a tweak to be made in 2024/25 vs the initial 2023/24 implementation currently added in this PR.

2023-12-21 10:47 UTC, SLornieCYC requested changes

2023-12-21 10:47 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +        ]
This needs to be `LS` not `LA`!

2023-12-21 10:47 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +    )
How about a test where the child is missing entirely from the `SWEpisodes` dataframe?

2023-12-21 10:47 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +            {"CHILD": "child4", "DEC": pd.NA, "LA": "xx"},
As above, this needs to be `LS` not `LA`!

2023-12-21 10:47 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +            {"CHILD": "child4", "DEC": pd.NA, "LA": "xx"},
How about tests here to ensure non-null `DEC` are correctly excluded? Ditto a null `DEC` and V3 or V4 `LS` episode.

2024-01-03 10:38 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +    )
So I've added this, and it passes, but I'd like a sense check; should it pass?

2024-01-04 11:44 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +    )
Those additional tests all looks fine.  How about adding **child8** to `fake_epi` (`DEC` = pd.NA and `LS` = xx) without a corresponding line in `fake_swe`?  I would expect that to fail.  You probably need to assert result on `fake-epi` rather than `fake_swe` for that.

2024-02-26 11:28 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW01STG1.py
> +    )
Two months later, I've found time to add the one line of code needed for this 😆

2024-02-29 09:16 UTC, SLornieCYC commented
> > now additionally closes #701
> 
> Is there a commit you've not pushed for this addition? The second issue is a tweak to be made in 2024/25 vs the initial 2023/24 implementation currently added in this PR.

Think this is the only bit left to resolve on this one.

2024-03-12 12:27 UTC, SLornieCYC approved these changes
Think this looks good now!

2024-04-16 08:16 UTC, merged