Amend/error503 d
data-to-insight/csc-validator-be-903 pull request #773
Opened 2024-04-24 12:31 UTC by WillLP-code

closes #772 

Also fixes typo in SW16aSTG2 which prevented running rules

2024-04-25 09:23 UTC, SLornieCYC commented on lac_validator/rules/rule_utils.py
> +            return {"Episodes": err_list}
What you've done here is clever but now I'm wondering if this could be tweaked to handle the variation entirely within this function (`field_different_from_previous`) without needing the optional parameter or changes to the individual rule entry?

For example:

1) Bring in `metadata[collectionYear]`
2) Do the normal `err_mask` filter (handling all field types)
3) Put the special handling after `err_mask` but before setting `err_list` to the unique index
4) Change your new if to `if field =='PLACE' and collectionYear == '2024/25':` with the "true" part additionally filtering `err_mask` to exclude K3 == H5
5) Set `err_list` to the unique index as normal

This I think would be cleaner and mean that if further code equivalency is needed in future years, those can also be handled as separate if statements in the same way?  Rather than potentially resulting in a proliferation of optional parameters between the function and the individual rules.

2024-05-10 08:23 UTC, SLornieCYC requested changes

2024-05-10 08:23 UTC, SLornieCYC commented on lac_validator/rules/rule_utils.py
> +            )
Does this need another set of brackets somewhere so that it **only** excludes K3 (in `this_one`) when `pre_one` (for the same row) is H5?  I can't decide how the engine will handle err_mask & expression & expression.

If `this_one` is K3 and `pre_one` is e.g. U6 we still want that to flag as an error, ditto where `pre_one` is H5 and `this_one` is anything other than K3.

2024-05-10 08:23 UTC, SLornieCYC commented on lac_validator/rules/lac2024_25/rule_503D.py
We shouldn't need this copy of the rule file at all now if handling the special case entirely within the rule_util function?  EDIT apart from adding the metadata to the rule test...

2024-05-10 08:23 UTC, SLornieCYC commented on lac_validator/rules/rule_utils.py
> +        collection_year = dfs["metadata"]["collectionYear"]
Adding this here does mean metadata/collection year needs to be included in the test data for **all rules** (in all years) that call the `field_different_from_previous` function. i.e. all of the other alphabetised parts of 503.

2024-05-10 08:33 UTC, SLornieCYC commented on lac_validator/rules/rule_utils.py
> +            )
I think it might need be a negation rather than an addition?  Like this maybe?

```
if (field == "PLACE") & (collection_year == "2024"):
            err_mask = (
                err_mask
                & ~((merged_co[this_one].astype(str) == "K3")
                & (merged_co[pre_one].astype(str) == "H5"))
            )
```

A few additional tests to handle the special case might be useful here.

2024-05-13 14:10 UTC, WillLP-code commented on lac_validator/rules/lac2024_25/rule_503D.py
For the metadata reason, I suggest we keep it?

2024-05-14 12:33 UTC, SLornieCYC commented on lac_validator/rules/lac2024_25/rule_503D.py
Hmm in which case I think it would be clearer to:
1) **Only** include 503D in the 2024/25 folder (the one the special case actually applies to).
2) Update the other 503 parts with metadata in the earliest year they exist (you've already done this in 2022/23) but then **omit** them from the later year folders (because there is no change to those rules or their behaviour).
3) Take your comment out of the 2024/25 version of 503D (where the year **does** matter) and instead add it to all of the 503 parts in 2022/23 (where it doesn't):

```# For the test, this doesn't affect anything except how the data is handled
    # by the field_different function, so it doesn't matter that the years
    # in the test dfs are not accurate to this collection year
    # As seen in conftest collection year is read in as XXXX/XX and stored in metadata
    # as the first four characters using [:4] in _process_metadata in datastore```

2024-05-14 14:46 UTC, SLornieCYC approved these changes
This looks good to me now!

2024-05-15 07:39 UTC, merged