Rules SW11aSTG2 and SW11bSTG2
data-to-insight/csc-validator-be-903 pull request #787
Opened 2024-06-21 09:13 UTC by WillLP-code

Had a quick go at these using the original SW11STG2 code, just changing what the error rows look for.

a looks for an SW_DECOM within +/- 5 days of the previous SW_DEC if the SW_DEC is more than 5 days before the end of the collection

b looks for ANY SW_DECOM if the SW_DEC is after 5 days before the end of the collection.

As always, I'm going by the logic, not the words though, so their suggested coding may not match up to what they're really looking for.

2024-06-21 13:30 UTC, SLornieCYC requested changes
Looks good but think there are a few issues.

2024-06-21 13:30 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11aSTG2.py
> +        )
Don't we need to merge on CHILD here as well, to make sure that the episodes we're comparing are actually for the same child?

2024-06-21 13:30 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
>              suffixes=("", "_prev"),
Ditto here (l32-38).  Don't we need to merge on CHILD here as well, to make sure that the episodes we're comparing are actually for the same child?

2024-06-21 13:30 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
I think this line (table index 8) should fail because it ended >= collection_end -5 and there's no subsequent episode?  May be related to other comments about making sure we're comparing for same child.

2024-06-21 13:30 UTC, SLornieCYC commented on tests/test_utils.py
> +    assert len(registry) == 312
Think this still wants to be 311 as we need to remove the originally coded SW11STG2 too.  (These two new rules replaced that one in a later version of the rules from the same return year).  Not sure whether we just delete the SW11STG2 rule file entirely or leave it and add the ID to the deleted rules string for the same year?

2024-06-24 07:26 UTC, WillLP-code commented on tests/test_utils.py
> +    assert len(registry) == 312
So I changed SW11STG2 to SW11aSTG2, and added SW11bSTG2, so I think it makes sense to add one to the rule number? I can add SW11STG2 back and have it in the deleted rules, you're right, but I think that's still 312?

2024-06-24 08:21 UTC, SLornieCYC commented on tests/test_utils.py
> +    assert len(registry) == 312
Oh, right.  So you did!  All good then!

2024-06-24 08:33 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW11aSTG2.py
> +        )
good catch, this wasn't in the original rule and I didn't even look at this bit!

2024-06-25 09:54 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
I've been thinking about this, shouldn't LOTS of these rows fail as there are SW_DEC later than collection_end - 5? For istance, child 3 has a SW_DEC on 03/04/2000 (which whilst it's later than the collection period, is after the end - 5 which is what the rule cares about) and no subsequent DECOM?

2024-06-25 09:55 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
If this is true, I have a bunch of changes ready to commit that I think work, and if not, it's back to the grindstone to work out how to find children that fit in with this rule

2024-06-26 14:33 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
>              suffixes=("", "_prev"),
I see you've taken different approaches in the two rules.  On 11a you've used `same_child = before_end["CHILD"] == before_end["CHILD_prev"]` and here in 11b you've included CHILD in the merge.  Obviousy the two methods don't quite return the same thing so we'll have to check (via the test data) which one gets us what we need.

2024-06-26 14:44 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
I think for child 3 it's actually entirely appropriate for this rule to ignore the rows because both SW_DECOM values are after 31 March (collection_end).  They'd be flagged in another rule as being invalid!

For child 1 (to use another example) I think the first row should technically fail because the subsequent row SW_DECOM is not between the first row SW_DEC (in scope of the collection_end -5) and 31 March, and the second row should be ignored because the SW_DECOM is after 31 March (but again, handled as an error elsewhere).

2024-06-27 08:11 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
Okay so would it be, do you think, appropriate to check for values between collection_end - 5 and collection end?

I'm just trying to puzzle out how we get child 5 to fail, but not others. I'm also not entirely sure the ingress would make a row like the second row for child 6 where they have an NA in both SW_DECOM and SW_DEC, which at the moment is being used to determine if they have an appropriate DECOM

2024-06-27 09:16 UTC, SLornieCYC commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
Yeah, I think if `SW_DEC_prev` is between `collection_end -5` and `collection_end` then we want the `SW_DECOM` value on the same merged row to be between `SW_DEC_prev` and `collection_end`.

That should work for child 5 based on the outer join merge (actual data on the _prev side and pd.NA on the other?).  If a row with two pd.NA dates wouldn't make it through Ingress (and to be fair, even if it did it would be subject to multiple errors!) I think the outer join merge should still return the null line for the comparison as with child 5?

2024-07-03 11:08 UTC, WillLP-code commented on lac_validator/rules/lac2023_24/rule_SW11bSTG2.py
> +            {"CHILD": "5", "SW_DECOM": "01/04/2000", "SW_DEC": "30/03/2000"},
Okay, with some finagling in the last commit I've found a way to a) include only the rows within collection_end >= SW_DEC >= collection_end - 5 and b) a way to get children who have multiple SW_DEC all within that timeframe, but no following NA SW_DECOM which would be needed. There may still be some edge cases these don't capture though... as there always seem to be!

2024-11-25 13:20 UTC, merged